### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by MosheM2** [yanissi/google-business-review-export-tool-tutorial#1]
Hey!
I was wondering what python version I need to use to get this running?

**Comment by MosheM2** [comment]
Ok now I know python 3.9 is fine. I tryed running it in the editor console instead of powershell and couldnt get started. 
After getting this right I get following error after pressing the submit button:

2021-11-04 17:38:21.936 Traceback (most recent call last):

  File "C:\Users\XXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\streamlit\script_runner.py", line 354, in _run_script
    exec(code, module.__dict__)
  
File "C:\xampp\htdocs\google-business-review-export-tool-tutorial\exportBusinessReviews.py", line 47, in <module>
    for review in results[0]['tasks'][0]['result'][0]['items']:

IndexError: list index out of range

Any ideas? 
Greetings Moe
